/* Generated by build.py. Cache name changes whenever the page or any asset
   does, so a new deploy replaces the old cache instead of shadowing it. */
var C = 'phuquoc-f2a7d13c58';
var ASSETS = ["./", "./index.html", "./manifest.webmanifest", "./fonts/outfit.woff2", "./fonts/jakarta.woff2", "./icons/icon-192.png", "./icons/icon-512.png", "./icons/apple-touch-icon.png", "./img/b1.66eaeec6.webp", "./img/b2.42ae33c8.webp", "./img/b3.01a27b6a.webp", "./img/b4.c6967b12.webp", "./img/grandworld.ad5d52e7.webp", "./img/honthom.e394ad1f.webp", "./img/jw.971109d3.webp", "./img/kissbridge.5853ce28.webp", "./img/lafesta.5f7ba847.webp", "./img/melia.45e7ce32.webp", "./img/sao.a9e1034a.webp", "./img/vinpearl.0e8c947b.webp"];
self.addEventListener('install', function(e){
  e.waitUntil(caches.open(C).then(function(c){ return c.addAll(ASSETS); }).then(function(){ return self.skipWaiting(); }));
});
self.addEventListener('activate', function(e){
  e.waitUntil(caches.keys().then(function(ks){
    return Promise.all(ks.map(function(k){ return k===C ? null : caches.delete(k); }));
  }).then(function(){ return self.clients.claim(); }));
});
self.addEventListener('fetch', function(e){
  var u = new URL(e.request.url);
  if(e.request.method !== 'GET' || u.origin !== location.origin) return;   // the weather call goes straight to the network
  var doc = e.request.mode === 'navigate' || u.pathname === '/' || u.pathname.endsWith('/index.html');
  if(doc){
    // only the app itself refreshes the cached copy; any other page on this
    // origin must not be written in over it
    var isApp = u.pathname === '/' || u.pathname.endsWith('/index.html');
    e.respondWith(fetch(e.request).then(function(r){
      if(isApp){ var copy = r.clone(); caches.open(C).then(function(c){ c.put('./index.html', copy); }); }
      return r;
    }).catch(function(){ return isApp ? caches.match('./index.html') : Response.error(); }));
    return;
  }
  e.respondWith(caches.match(e.request).then(function(m){ return m || fetch(e.request); }));
});
